services:
  - type: static
    name: har-analyzer-frontend
    buildCommand: npm install && npm run build
    publishDir: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://har-analyzer-backend.onrender.com
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.x
    routes:
      - type: rewrite
        source: /*
        destination: /index.html